using NeonWindows.ABI.UI.Scaling;
using NeonWindows.UI.Scaling;

// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("Testing null DPI_AWARENESS_CONTEXTs...");
Console.WriteLine((new DPI_AWARENESS_CONTEXT(0)).IsNull);
Console.WriteLine("Testing equal DPI_AWARENESS_CONTEXTs...");
DPI_AWARENESS_CONTEXT d1 = new(int.MinValue);
DPI_AWARENESS_CONTEXT d2 = new(int.MinValue);
Console.WriteLine(d1 == d2);
Console.WriteLine("Testing native api NtUserGetProcessDpiAwarenessContext with invalid parameters...");
Console.WriteLine(ProcessDpiContextApi.NtUserGetProcessDpiAwarenessContext(int.MinValue).IsNull);
Console.ReadKey();
Console.WriteLine($"CurrentProcessDpiAwarenessMode: {AppDpiAwareness.CurrentProcessDpiAwarenessMode}");
Console.WriteLine($"CurrentThreadDpiAwarenessMode: {AppDpiAwareness2.CurrentThreadDpiAwarenessMode}");
Console.ReadKey();
Console.WriteLine("Testing native api NtUserSetProcessDpiAwarenessContext...1");
Console.WriteLine(ProcessDpiContextApi.NtUserSetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT.DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_MIXED, false));
Console.ReadKey();
Console.WriteLine($"CurrentProcessDpiAwarenessMode: {AppDpiAwareness.CurrentProcessDpiAwarenessMode}");
Console.WriteLine($"CurrentThreadDpiAwarenessMode: {AppDpiAwareness2.CurrentThreadDpiAwarenessMode}");
Console.ReadKey();
Console.WriteLine("Testing native api NtUserSetProcessDpiAwarenessContext...2");
Console.WriteLine(ProcessDpiContextApi.NtUserSetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT.DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2_MIXED, false));
Console.ReadKey();
Console.WriteLine($"CurrentProcessDpiAwarenessMode: {AppDpiAwareness.CurrentProcessDpiAwarenessMode}");
Console.WriteLine($"CurrentThreadDpiAwarenessMode: {AppDpiAwareness2.CurrentThreadDpiAwarenessMode}");
Console.ReadKey();
Console.WriteLine("Testing native api NtUserSetProcessDpiAwarenessContext...3");
Console.WriteLine(ProcessDpiContextApi.NtUserSetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT.DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2_MIXED, true));
Console.ReadKey();
Console.WriteLine($"CurrentProcessDpiAwarenessMode: {AppDpiAwareness.CurrentProcessDpiAwarenessMode}");
Console.WriteLine($"CurrentThreadDpiAwarenessMode: {AppDpiAwareness2.CurrentThreadDpiAwarenessMode}");
Console.ReadKey();
Console.WriteLine("Setting ThreadDpiAwarenessContext to null...");
Console.WriteLine(!ThreadDpiContextApi.SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT.Null).IsNull);
Console.ReadKey();
Console.WriteLine($"CurrentThreadDpiAwarenessMode: {AppDpiAwareness2.CurrentThreadDpiAwarenessMode}");
Console.ReadKey();
