<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\NeonWinModernBase\NeonWinModern.props" />
	<PropertyGroup>
		<TargetFramework>net462</TargetFramework>
		<LangVersion>10.0</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\NeonWin32UICore\NeonWin32UICore.csproj" />
		<ProjectReference Include="..\NeonWinComModel\NeonWinComModel.csproj" />
		<ProjectReference Include="..\NeonWinModernCoreFx\NeonWinModernCoreFx.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="UI\Modern\Desktop\" />
	  <Folder Include="UI\Modern\Xaml\Desktop\" />
	</ItemGroup>
</Project>
