<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\NeonWinModernBase\NeonWinModern.props" />
	<Import Project="..\NeonWinModernBase\OldTFAdaptive.props" />
	<PropertyGroup>
		<TargetFramework>net462</TargetFramework>
		<PackageId>NeonWindows.ModernApp.Fx</PackageId>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyTitle>NeonWindows Modern App Library for Old .NET Platforms</AssemblyTitle>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\NeonWinComModel\NeonWinComModel.csproj" />
		<ProjectReference Include="..\NeonWinModernCoreFx\NeonWinModernCoreFx.csproj" />
		<ProjectReference Include="..\NeonWinModernFormsFx\NeonWinModernFormsFx.csproj" />
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="UI\Modern\Desktop\CoreAppViewWindow.cs">
	    <SubType>Form</SubType>
	  </Compile>
	  <Compile Update="UI\Modern\Desktop\Core\CoreUIHostWindow.cs">
	    <SubType>Form</SubType>
	  </Compile>
	  <Compile Update="UI\Modern\Xaml\Desktop\DesktopXamlWindow.cs">
	    <SubType>Form</SubType>
	  </Compile>
	  <Compile Update="UI\Modern\Xaml\Desktop\WindowsXamlHostBase.cs">
	    <SubType>Component</SubType>
	  </Compile>
	</ItemGroup>
</Project>
