<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>NeonWindows</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<UseUwp>true</UseUwp>
		<UseUwpTools>false</UseUwpTools>
		<IsAotCompatible>true</IsAotCompatible>
		<ProductVersion>0.0.8.0</ProductVersion>
		<FileVersion>$(ProductVersion)</FileVersion>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\NeonWinModernCoreI\NeonWinModernCoreI.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="ABI\UI\Composition\" />
	  <Folder Include="UI\Modern\Xaml\" />
	</ItemGroup>
</Project>
