<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\NeonWinModernBase\NeonWinModern.props" />
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<UseUwp>true</UseUwp>
		<UseUwpTools>false</UseUwpTools>
		<IsAotCompatible>true</IsAotCompatible>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\NeonWinModernCoreI\NeonWinModernCoreI.csproj" />
	</ItemGroup>
</Project>
