<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="NeonWinModern.props" />
	<Import Project="OldTFAdaptive.props" />
	<PropertyGroup>
		<TargetFramework>netstandard1.1</TargetFramework>
		<PackageId>NeonWindows.ModernApp.Base</PackageId>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyTitle>Base Library for NeonWindows Modern App</AssemblyTitle>
	</PropertyGroup>
</Project>
