<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard1.1</TargetFramework>
		<RootNamespace>NeonWindows</RootNamespace>
		<LangVersion>10.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
		<ProductVersion>0.12.2.0</ProductVersion>
		<FileVersion>$(ProductVersion)</FileVersion>
	</PropertyGroup>
</Project>
