<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\NeonWinModernBase\NeonWinModern.props" />
	<Import Project="..\NeonWinModernBase\OldTFAdaptive.props" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<PackageId>NeonWindows.ModernApp.Core.Fx</PackageId>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyTitle>NeonWindows Modern App Core Library for Old .NET Platforms</AssemblyTitle>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NeonWinModernCoreI\NeonWinModernCoreI.csproj" />
	  <ProjectReference Include="..\WinRTPolyfillsFx\WinRTPolyfillsFx.csproj" />
	</ItemGroup>
</Project>
