<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\NeonWinModernBase\NeonWinModern.props" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>10.0</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NeonWinModernCoreI\NeonWinModernCoreI.csproj" />
	  <ProjectReference Include="..\WinRTPolyfillsFx\WinRTPolyfillsFx.csproj" />
	</ItemGroup>
</Project>
