<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\NeonWinModernForms\NeonWinModernForms.Common.props" />
	<PropertyGroup>
		<TargetFramework>net462</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>
</Project>
